recipe: default.v1
language: en
assistant_id: huddlex_2026

pipeline:
  - name: CompactLLMCommandGenerator
    llm:
      model_group: nebius_command_llm
    flow_retrieval:
      active: false

policies:
  - name: FlowPolicy
